# Credit: Workflow configs inspired from https://github.com/Wynntils/Wynntils
name: Python Format & Test

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    branches: [main]

jobs:
  format-and-test:
    name: Run Python Tests
    if: "! github.event.pull_request.draft"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.PRIVATE_TOKEN }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set Up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13.0"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff black
          pip install -r requirements.txt

      - name: Format with Ruff and Black
        run: |
          python -m ruff check --fix --exit-zero --no-cache .
          python -m black .

      - name: Commit Format
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: "FAZuH-bot"
          commit_user_email: "fazuhhh@proton.me"
          commit_message: "ci: ruff and black formatting"

      - name: Test with pytest
        run: |
          python -m pytest --cache-clear tests/
